# Generated by Django 4.2.7 on 2025-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image for the book', null=True, upload_to='covers/'),
        ),
    ]
